# Generated by Django 2.2.7 on 2020-01-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.URLField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('B', 'Blog'), ('J', 'Journal'), ('R', 'Book Review'), ('L', 'DUThinks'), ('N', 'LPRNews'), ('C', 'Call For Paper')], max_length=1),
        ),
    ]
