# Generated by Django 2.2.7 on 2020-01-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200103_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='share_count',
            field=models.IntegerField(default=0),
        ),
    ]
